### ISSUE TITLE
Todo:

### ISSUE THREAD

**Issue by tealicious** [tealicious/sweet-apple-acres#1]
- [x] Cart + Purchase UI/UX
- [x] Check all pages with Siteimprove extension for WCAG compliance
- [x] Write E2E tests against business requirements
- [ ] ~Write an example unite test or two~ update: **dun'wanna**
